### ISSUE TITLE
Implement push notifications

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/appbuilders18app#1]
- https://firebase.google.com/docs/cloud-messaging/

**Comment by BalestraPatrick** [comment]
Working on iOS, missing configuration on Android.

**Comment by simonedavico** [comment]
How should the integration in app work exactly? I understand how to setup the `FCM` package ([docs](https://rnfirebase.io/docs/v3.3.x/messaging/android)), but on the iOS side it looks like the integration is done natively, and not by using the js bridge. Should the same be done to Android? Or maybe it would be better to leverage the js methods for both platforms?

**Comment by BalestraPatrick** [comment]
@simonedavico From the docs it seems that the Firebase SDK does everything on its own (like on iOS it swizzles the platform methods to register for the tokens). You could try to configure the package as said in the docs and install the app on a device, then let me know and I'll try to send a test push notification from the console 👍

**Comment by simonedavico** [comment]
Got it!
