### ISSUE TITLE
Make Android version compile correctly

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/appbuilders18app#11]
Right now, the Android project doesn't complain due to some gradle error when integrating the required dependencies. This is probably due to the maximum number of methods in a module.
The iOS version isn't affected.

**Comment by simonedavico** [comment]
@BalestraPatrick I'll start with this one! Feel free to assign it :)

**Comment by simonedavico** [comment]
Note to self: maybe related, since the app uses `device-info` and `maps`:

https://github.com/invertase/react-native-firebase/issues/247#issuecomment-315715926
