### ISSUE TITLE
Upgrade react-native to latest version

### ISSUE THREAD

**Issue by simonedavico** [BalestraPatrick/appbuilders18app#13]
Latest react-native versions solve a multitude of bugs and improve the API and performance of many primitives. Follow the [upgrade guide](http://facebook.github.io/react-native/docs/upgrading.html) on the docs to jump to the latest version (currently [0.54](https://github.com/facebook/react-native/releases/tag/v0.54.0)).

**Comment by simonedavico** [comment]
The current version of `react-native-maps` (0.20.1) is not compatible with the latest react-native release (0.54).

**Comment by BalestraPatrick** [comment]
We could still upgrade to 0.51 which is supported by `react-native-maps` @simonedavico?

**Comment by simonedavico** [comment]
I tried upgrading to 0.53 (with `react-native-git-upgrade 0.53.0`). 
The patch process did not terminate, but I still had a `patch` to be applied manually (see [this comment](https://github.com/facebook/react-native/issues/12112#issuecomment-284491701)). 

Unfortunately, I don't know the iOS ecosystem well enough to solve the conflicts on the `xcodeproj` files :( if you want, we can try to run the upgrade procedure together, surely you know more on iOS than me!
