### ISSUE TITLE
Find better alternative to show tweets in speaker view to avoid double scrolling

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/appbuilders18app#17]
Right now we are using a nested `webView` to show tweets, we should probably make it a separate view or find a better alternative.

**Comment by simonedavico** [comment]
Is it a requirement to show them in app? Couldn't we just open the speaker's twitter feed externally?

**Comment by BalestraPatrick** [comment]
Yes, I was thinking of doing that. It would also be better for the user to open their preferred Twitter client (on iOS we should support Twitter and Tweetbot). What we could do, is to add a preference in the settings to let the user choose their preferred Twitter client (probably on Android there's only the official Twitter app?).

After we have that preference, we can simply add a button in the navigation bar to open the speaker profile in the preferred client via a URL scheme.

**Comment by simonedavico** [comment]
On Android there are multiple twitter clients available, but the `Linking` API opens the user's preferred one (or asks to choose if there is no preferred one). In fact, this is already what happens after closing issue #9.  I guess the same is true on the iOS side :)

**Comment by BalestraPatrick** [comment]
Unfortunately on iOS there isn't any API to figure what the user's preferred client is and we have to provide it ourselves. So since this works already on Android, we should probably only add this feature on the iOS side. What do you think?

**Comment by simonedavico** [comment]
Yep, consistency is best. We could try passing the `Linking` api a twitter URL and see what happens on iOS.

Regarding iOS, React Native docs [state](https://facebook.github.io/react-native/docs/linking.html#canopenurl) that as long as the `LSApplicationQueriesSchemes ` property is configured it should work similarly to Android.
