### ISSUE TITLE
Twitter handles on speaker page open Danny's profile

### ISSUE THREAD

**Issue by mariobodemann** [BalestraPatrick/appbuilders18app#23]
Hey,

Opening the speaker page and clicking on the little bird, I can see only Danny's Twitter profile...
![screenshot_20180416-142740](https://user-images.githubusercontent.com/1162562/38809066-93bccc3a-4182-11e8-87fa-983b15c747f6.png)
![screenshot_20180416-142743](https://user-images.githubusercontent.com/1162562/38809067-93e874c0-4182-11e8-9643-11317e955f4c.png)

**Comment by BalestraPatrick** [comment]
Ah! This was fixed but we didn’t submit an update to the Google Play yet I guess
