### ISSUE TITLE
Modify `openLink` to open Links in Android WebView instead of SafariView

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/appbuilders18app#9]
Right now, all links are opened is `SafariView` since I was testing on iOS. All links are failing to open correctly since we based on the platform we are running on, we are to open the link with a different API.

**Comment by simonedavico** [comment]
Wouldn't [Linking](https://facebook.github.io/react-native/docs/linking.html#opening-external-links) be a cross-platform solution without external dependencies?

**Comment by BalestraPatrick** [comment]
Yes it would but I think iOS users expect to be able to use `SFSafariViewController` on iOS, so that's why it's better to have a platform-dependent experience in this case. How does Android usually handle this? Just open the default browser? If so, if Safari isn't available, we can directly fallback to use Linking.

**Comment by simonedavico** [comment]
Android users may have preferences to open links in external browser (usually Chrome, but there are a lot of alternatives), or an in-app webview. Your proposed solution looks nice to me, I'll give it a try 👍

**Comment by BalestraPatrick** [comment]
Doesn't Linking use the default browser (or asks to choose one)? I've seen that behavior happening on some Android apps for the very short time I used to run Android 😄

**Comment by simonedavico** [comment]
Yes, what I meant with the previous comment is that it leverages the user's preference, which should work like this:

- If there is only one app that can handle the external link, use that app;
- If there are multiple apps and the user has not chosen to use always a given one, ask to choose;
- In the user has previously chosen a favourite app, it directly uses that.

I think there is one more case (there should be a setting in Chrome to prefer an in-app webview over opening the browser directly), but I guess we can try the linking solution and test every case, I'm no expert either :)
